### ISSUE TITLE
Port D has a 11th line

### ISSUE THREAD

**Issue by gergoerdi** [klangner/sam3x#10]
Port D has an 11'th line (i.e. D.10) and it is connected to pin 32 of the Arduino Due,  on the double-row header. See e.g. here: http://www.robgray.com/temp/Due-pinout-WEB.png

The following line should be changed to allow `line == 10`:
https://github.com/klangner/sam3x/blob/a34e0e2241951f49e1a990e05fe45175fafb95c5/src/hal/pio.rs#L129

**Comment by klangner** [comment]
Thanks!
